/**
 * Generated by scripts/process-landscape-images.mjs — do not edit.
 * Sync generated files with `pnpm images:sync` before removing local assets.
 */
export const LANDSCAPE_WIDTHS = [320, 640, 960, 1280, 1920] as const;
export const LANDSCAPE_ENTRIES = [
	{ originalName: 'Carson Pass 2-Winnemucca Lk-2.jpg', slug: 'carson-pass-2-winnemucca-lk-2' },
	{ originalName: 'Easter Sierra Winter 2014-11.jpg', slug: 'easter-sierra-winter-2014-11' },
	{
		originalName: 'Eastern Sierra Summer 2012-3123-Edit.jpg',
		slug: 'eastern-sierra-summer-2012-3123-edit'
	},
	{ originalName: 'Kiva Beach Sunset-9.jpg', slug: 'kiva-beach-sunset-9' },
	{ originalName: 'Mt. Muir From Trail Crest-6539.jpg', slug: 'mt-muir-from-trail-crest-6539' },
	{ originalName: 'Sierra Fall-8937.jpg', slug: 'sierra-fall-8937' },
	{ originalName: 'Tahoe Summer 2013-8533.jpg', slug: 'tahoe-summer-2013-8533' },
	{ originalName: 'Tunnel View-5282.jpg', slug: 'tunnel-view-5282' },
	{ originalName: 'Tunnel View-Edit-2.jpg', slug: 'tunnel-view-edit-2' },
	{
		originalName: 'Volcanic Tablelands Spring 2014-1.jpg',
		slug: 'volcanic-tablelands-spring-2014-1'
	},
	{ originalName: 'Yosemite May 2015-4010.jpg', slug: 'yosemite-may-2015-4010' },
	{ originalName: 'Yosemite Spring 2016-1.jpg', slug: 'yosemite-spring-2016-1' }
] as const;
export const LANDSCAPE_BASE = 'placeholders/landscapes';
